### ISSUE TITLE
an update on the dot position

### ISSUE THREAD

**Issue by kiyoyabe** [Subaru-PFS/ets_fiber_assigner#2]
Hi @mreinecke ,

Sorry that I had forgotten to tell you an update on the dot position. Now the dot position is 2.35 mm from the cobra center (I think it was 1.19 mm in the previous information).

Cheers,
Kiyoto

**Comment by mreinecke** [comment]
Dear Kiyoto,

thank you for the update! I will adjust the ETS code accordingly.

Cheers,
  Martin
